name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
      env:
        CI: true
    - run: |
        echo Publish to github
        git checkout -b $TARGET_BRANCH
        git rm -rf .
        rm -rf node_modules
        mv build/* .
        rm -rf build
        git add -f --ignore-errors --all
        git -c user.name='Zoe' -c user.email='hi@zoe.im' commit -m ":tada: release ui"
        ls -al
        git push -f -q https://$GH_USER:$GH_TOKEN@github.com/$BUILD_REPOSITORY_ID $TARGET_BRANCH
